spring:
  application:
    name: store-spring-data-jpa
  datasource:
    host: localhost
    port: 5433
    dbname: store-spring-data-jpa-db
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}
    username: postgres
    password: password
  jpa:
    # outputs the SQL statements on the console
    show-sql: true
